name: Spring boot CI

on:
  push:
    branches: [main]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Copy the repository
        uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'adopt'
          cache: maven
      - name: Build and test with Maven
        run: mvn --batch-mode --update-snapshots package -Dspring-boot.run.profiles=prod
      - name: Configure SSH communication
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/raspberry.key
          chmod 600 ~/.ssh/raspberry.key
          cat >>~/.ssh/config <<END
          Host raspberry
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/raspberry.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
      - name: Upload artifact
        run: |
          scp target/classes/universe.db target/classes/millennium-falcon.json raspberry:~/dataiku/backend
          scp target/*.jar raspberry:~/dataiku/backend/app.jar
      - name: Relaunch Docker containers
        run: ssh raspberry 'docker-compose -f ~/dataiku/docker-compose.yml up --build -d'
      - name: Clean up
        if: always()
        run: rm -rf ~/.ssh/
