name: Java CI

on: [push]
#on:
#  push:
#    branches:
#      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'adopt'
          cache: maven
      - run: mvn --batch-mode --update-snapshots package
      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: ghcr.io/hugoisep/dataiku-millenium-falcon-challenge-backend:latest
          push: true
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/raspberry.key
          chmod 600 ~/.ssh/raspberry.key
          cat >>~/.ssh/config <<END
          Host raspberry
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/raspberry.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.USER }}
          SSH_KEY: ${{ secrets.PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.HOST }}
      - name: Login to Github registry
        run: ssh raspberry 'echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u hugoISEP --password-stdin'
      - name: Check if successful
        run: ssh raspberry 'docker run -p 8080:8080 --network global-network --name millennium-falcon-backend ghcr.io/hugoisep/dataiku-millenium-falcon-challenge-backend:latest'
