name: Java CI

on: [push]
#on:
#  push:
#    branches:
#      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'adopt'
          cache: maven
      - run: mvn --batch-mode --update-snapshots package
      - run: mkdir millennium-falcon-package && cp target/*.jar millennium-falcon-package && cp target/classes/millennium-falcon.json  millennium-falcon-package && cp target/classes/universe.db  millennium-falcon-package
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: millennium-falcon-package
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/raspberry.key
          chmod 600 ~/.ssh/raspberry.key
          cat >>~/.ssh/config <<END
          Host raspberry
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/raspberry.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.USER }}
          SSH_KEY: ${{ secrets.PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.HOST }}
      - name: Transfer package
        run: scp -r ./millennium-falcon-package raspberry:~/dataiku/backend/millennium-falcon-package
      - name: Relaunch Docker containers
        run: ssh raspberry 'docker-compose -f ~/dataiku/docker-compose.yml up --build -d'
